import Head from 'next/head';
import { Header } from "./header/Header";

export function MainLayout({children, title}){
    return(
        <div className='wrapper'>
            <Head>
                <title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
            </Head>
            
            <Header />
            
            <main className='main'>{children}</main>
            {/* <Footer /> */}
        </div>
    )
}